### ISSUE TITLE
Folder Deletion Bug

### ISSUE THREAD

**Issue by JeremieGar** [alexandregpereira/Monster-Compendium#269]
## How to reproduce

1. Launch the app
2. Open the folder tab
3. Hold down on an existing folder
4. Click delete

![image](https://github.com/alexandregpereira/Monster-Compendium/assets/46535802/99809d54-014a-456e-b794-2c908344de49)

## Expected behavior

The folder disappears and is deleted.

## Actual behavior

The folder does not disappear 

## Additional information:
1. Google Pixel 5 - Android 14
2. App version 24.02.16.14489

**Comment by alexandregpereira** [comment]
Hi @JeremieGar. Thank you for reporting and sorry for the late reply.

I found the problem and fixed [here](https://github.com/alexandregpereira/Monster-Compendium/pull/274). Soon I new release version with the fix will be available on the Google Play.
